# Project information
site_name: Magellan TOOLBOX
site_description: 'Magellan TOOLBOX'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.magellan7-toolbox.stueber.de'

# Copyright
copyright: © 2021 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.magellan7-toolbox.de'

# Theming
theme: 
    name: material
    custom_dir: overrides
    language: de
    features:
        - navigation.tabs
        - navigation.instant
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Legal links
extra:
  legal:
    - label: Impressum
      link: https://www.stueber.de/imprint.php
    - label: Datenschutz
      link: https://legal.stueber.de/privacy.php

# Customization
extra_css:
    - assets/css/custom.css

# Plugins    
plugins:
    - search
    - img2fig

# Extensions    
markdown_extensions:
    - admonition
  
# Navigation  
nav:
- Allgemein:
  - Einführung: index.md
- Magellan Datenstruktur: datenstruktur/index.md
- Magellan-Importformat:
  - Einführung: importe/index.md
  - schulen.import.csv: importe/MagImp/schnittstellenformat_schulenimportcsv.md
  - betriebe.import.csv: importe/MagImp/betriebeimportcsv.md
  - lehrer.import.csv: importe/MagImp/lehrerimportcsv.md
  - sorgebe.import.csv: importe/MagImp/sorgebeimportcsv.md
  - verlage.import.csv: importe/MagImp/verlageimportcsv.md
  - lieferanten.import.csv: importe/MagImp/lieferantenimportcsv.md
  - medien.import.csv: importe/MagImp/medienimportcsv.md
  - exemplare.import.csv: importe/MagImp/exemplareimportcsv.md
  - klassen.import.csv: importe/MagImp/klassenimportcsv.md
  - schueler.import.csv: importe/MagImp/schuelerimportcsv.md
  - schueler_laufbahn.import.csv: importe/MagImp/schuelerlaufbahn_importcsv.md
  - schueler_fachdaten.import.csv: importe/MagImp/schuelerfachdatenimportcsv.md
  - schueler_sorgebe.import.csv: importe/MagImp/schuelersorgebeimportcsv.md
  - schueler_schulen.import.csv: importe/MagImp/schuelerschulenimportcsv.md
  - schueler_ausbildung.import.csv: importe/MagImp/schuelerausbildungimportcsv.md
  - Importieren: importe/MagImp/importieren_mit_dem_importassistenten.md
- Magellan-Scripting:
  - Einführung: scripting/index.md
  - Skripteditor: scripting/skripteditor.md
  - Skriptsprache: scripting/skriptsprache.md
  - Skriptkategorien: scripting/skriptkategorien.md
  - Bibliotheken: scripting/bibliotheken.md
  - Änderungen: scripting/aenderungen.md
 
